spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/products?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
    username: admin
    password: 123
    #schema: classpath:schema.sql
    #data: classpath:data.sql
    #initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

